###############################################################################
# CP/M-386 - .gitlab-ci.yml
# Copyright (c) 2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>
# SPDX-License-Identifier: MIT
# scspell-id: 97ccabb4-89f0-11f1-b031-80ee73e9b8e7
###############################################################################

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

###############################################################################

before_script:
  - |
    #
    echo -e "section_start:`date +%s`:Pre-setup_section[collapsed=true]\r\e[0K\033[0;36mPre-setup ...\033[0m" || true
  - dnf -y upgrade --allowerasing --setopt=install_weak_deps=True --setopt=keepcache=True
  - dnf -y install dnf-utils git --allowerasing --setopt=install_weak_deps=True --setopt=keepcache=True
  - git fetch origin
  - git checkout -B "$CI_COMMIT_REF_NAME" "origin/$CI_COMMIT_REF_NAME"
  - echo -e "section_end:`date +%s`:Pre-setup_section\r\e[0K" || true

###############################################################################

pages:
  stage: deploy
  image: quay.io/fedora/fedora:rawhide
  tags:
    - cpm386
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - |
      #
      echo -e "section_start:`date +%s`:Setup_section[collapsed=true]\r\e[0K\033[0;36mSetup ...\033[0m" || true
    - export TERM="xterm-color"
    - export TZ="UTC"
    - export LC_ALL="C"
    - dnf -y install advancecomp binutils brotli codespell coreutils cpmtools cppi devscripts-checkbashisms file gawk gcc glibc-devel.i686 glibc.i686 golang libatomic.i686 libatomic.x86_64 lz4 make nasm pigz reuse shellcheck zip --allowerasing --setopt=install_weak_deps=True
    - dnf -y clean all || true
    - mkdir -v -p "/etc/apt/apt.conf.d" || true
    - export GOPROXY="proxy.golang.org,direct"
    - export GOSUMDB="sum.golang.org"
    - export GOTOOLCHAIN="auto"
    - $(command -v go || printf '%s\n' "go") install "mvdan.cc/sh/v3/cmd/shfmt@master"
    - export PATH="$HOME/go/bin:$PATH"
    - rm -v -f ./.sizes.txt || true
    - echo -e "section_end:`date +%s`:Setup_section\r\e[0K" || true
    - |
      #
      echo -e "section_start:`date +%s`:Lint_section[collapsed=true]\r\e[0K\033[0;36mLinting ...\033[0m" || true
    - stdbuf -oL -eL make lint
    - echo -e "section_end:`date +%s`:Lint_section\r\e[0K" || true
    - |
      #
      echo -e "section_start:`date +%s`:Build_section[collapsed=true]\r\e[0K\033[0;36mCP/M-386 build ...\033[0m" || true
    - stdbuf -oL -eL make -Orecurse -j "$(nproc 2> /dev/null || printf '%s' 1)"
    - echo -e "section_end:`date +%s`:Build_section\r\e[0K" || true
    - |
      #
      echo -e "section_start:`date +%s`:Test_section[collapsed=true]\r\e[0K\033[0;36mCP/M-386 test ...\033[0m" || true
    - make test
    - echo -e "section_end:`date +%s`:Test_section\r\e[0K" || true
    - |
      #
      echo -e "section_start:`date +%s`:Deploy_section[collapsed=true]\r\e[0K\033[0;36mDeploy ...\033[0m" || true
    - make strip
    - mkdir -p "public/cpm386"
    - mv -v -f "fd.img" "public/cpm386/blankfd.img"
    - mv -v -f "hd.img" "public/cpm386/blankhd.img"
    - mv -v -f "cpm386.elf" "floppy.img" "mboot.sh" "public/cpm386"
    - cd public
    - touch "index.html"
    - zip -0 -X -D -j "cpm386.zip" "cpm386/cpm386.elf" "cpm386/floppy.img" "cpm386/mboot.sh" "cpm386/blankfd.img" "cpm386/blankhd.img"
    - advzip -z4 "cpm386.zip"
    - rm -v -r -f "./cpm386" || true
    - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k -v -Z -- "{}" \; || true
    - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec pigz -9 -f -k -m -v -- "{}" \; || true
    - echo -e "section_end:`date +%s`:Deploy_section\r\e[0K" || true
  artifacts:
    expire_in: 1 day
    paths:
      - public
  retry: 2
  timeout: 60 minutes
  interruptible: false

###############################################################################
